Repository edp5/kompagnon, pull requests merged in 2025-09, with the labels that each got.

#4 feat(api): Add a swagger to visualize routes
  api/config.js
  api/package-lock.json
  api/package.json
  api/server.js
  api/src/shared/health/routes.js
  api/swagger.js
Labels: Ready to merge, enhancement

#27 feat(api): remove static route
  api/server.js
Labels: Ready to merge, enhancement

#38 feat: setup the web app frontend
  .github/dependabot.yml
  .github/workflows/ci.yml
  README.md
  package.json
  scripts/configure.sh
  web/.editorconfig
  web/.gitattributes
  web/.gitignore
  web/.vscode/extensions.json
  web/eslint.config.mjs
  web/index.html
  web/jsconfig.json
  web/package-lock.json
  web/package.json
  web/public/favicon.ico
  web/sample.env
  web/src/App.vue
  web/src/adapters/api-check.js
  web/src/components/FooterComponent.vue
  web/src/main.js
  web/src/router/index.js
  web/tests/integration/components/FooterComponent.spec.js
  web/tests/setup.js
  web/tests/unit/App.spec.js
  web/tests/unit/adapters/api-check.spec.js
  web/tests/unit/main.spec.js
  web/tests/unit/router/index.spec.js
  web/vite.config.js
  web/vitest.config.js
Labels: Ready to merge, documentation, enhancement, dependencies

#50 tech(api): update isActive column default value and add column variable
  api/db/migrations/20250925085355_add-isActive-column-to-users-table.js
Labels: Ready to merge, tech

#49 tech(api): create database builder and first seeds
  api/db/database-builder/factory/build-user.js
  api/db/database-builder/index.js
  api/db/seeds/data/users.js
  api/db/seeds/seed.js
Labels: Ready to merge, tech

#52 tech(api): Create password service
  api/package-lock.json
  api/package.json
  api/src/identities-access-management/services/password-service.js
  api/tests/identities-access-management/integration/services/password-service.test.js
  api/tests/identities-access-management/unit/services/password-service.test.js
Labels: Ready to merge, dependencies, tech
